# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with: 
          path: ~/node_modules
          key: ${{ runner.OS}}-master-build-${{hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies    
        run: yarn
      - name: Build  
        run: yarn build
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 src/.vuepress/dist s3://taycan-docs.hupayx.io --acl public-read
      - name: Cache aws cloudfront
        run: aws cloudfront create-invalidation --distribution-id E1H6G4RXLGN0YG --paths "/*"
